Completed css-ecommerce-page exercise.
EuichangPark/rc0122-code-solutions pull request #32
Opened 2022-02-02 06:09 UTC by EuichangPark

![css-ecommerce-page](https://user-images.githubusercontent.com/96793078/152101884-2047022e-8b01-43d1-ac88-bd509926e0c0.PNG)

2022-02-02 18:29 UTC, TimelikeClosure requested changes

2022-02-02 18:29 UTC, TimelikeClosure commented on css-ecommerce-page/index.html
> +    </div>
There should be more space between the separator and the size. Also, the separator should be taller relative to the text:

---

![image](https://user-images.githubusercontent.com/16143771/152212722-668a4b96-8174-4062-a3f2-f0f69d94c555.png)

---

![image](https://user-images.githubusercontent.com/16143771/152212762-e72008ba-b7e0-4047-a0e1-0819cb2031fc.png)

2022-02-02 18:29 UTC, TimelikeClosure commented on css-ecommerce-page/index.html
> +      <p>New Arrivals</p>
Semantically, this should be a heading (`<h#>`), not a paragraph (`<p>`). Also, it needs a higher font-weight:

---

![image](https://user-images.githubusercontent.com/16143771/152213314-da826d3f-6ba6-4214-8a35-24bd7bb0a48f.png)

---

![image](https://user-images.githubusercontent.com/16143771/152213334-34e0f6f2-3f0f-479b-8c37-8fd862df8a3e.png)

2022-02-02 18:29 UTC, TimelikeClosure commented on css-ecommerce-page/index.html
> +      </div>
The capitalization is off here:

---

![image](https://user-images.githubusercontent.com/16143771/152213616-10de94fb-387d-4359-90f6-6fe10ec48419.png)

2022-02-02 18:29 UTC, TimelikeClosure commented on css-ecommerce-page/index.html
> +    </div>
The different products should have some space between their images:

---

![image](https://user-images.githubusercontent.com/16143771/152214098-4d2e3dd8-9846-450b-bddc-f94d2fbfa78b.png)

---

![image](https://user-images.githubusercontent.com/16143771/152214138-bad6cb34-3c82-4251-a7b8-179a29cf9bc2.png)

2022-02-02 18:29 UTC, TimelikeClosure commented on css-ecommerce-page/index.html
> +    </div>
Content-wise, related information should be grouped together as much as possible. For example, a product's image, name, size, and pricing are all related, so their grouping should take priority over, for example, grouping all the product images together.

---

![image](https://user-images.githubusercontent.com/16143771/152214469-7189dd2f-0bc4-44f0-a386-5ebc92c37086.png)

2022-02-02 18:29 UTC, TimelikeClosure commented on css-ecommerce-page/index.html
> +      </div>
The sale prices could use a little spacing around them within the background highlighting, and the background highlight color could be a little more subtle:

---

![image](https://user-images.githubusercontent.com/16143771/152215258-8e9b6064-4d51-4a68-8d01-607333fa349f.png)

---

![image](https://user-images.githubusercontent.com/16143771/152215303-47550e9c-28d8-41c9-832a-2676d5df617a.png)

2022-02-03 17:42 UTC, Zhiwutian approved these changes
👍🏼

2022-02-09 20:25 UTC, merged